---
title: JumperLuko
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: Jumper.Luko@gmail.com
description: Olá, pode me chamar de Jumper, e eu gosto muito de Web Design e uma diversidade
  de coisas do mundo da tecnlogia.
baseurl: ''
url: ''
twitter_username: JumperLuko
github_username: JumperLuko
permalink: "/:year/:month/:title/"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
